import pyautogui
from time import sleep

pyautogui.rightClick(318,751)
sleep(2)
pyautogui.click(300,625)
sleep(15)
pyautogui.click(118,46)
sleep(0.5)
pyautogui.typewrite('facebook.com')
pyautogui.press('enter')
sleep(15)
pyautogui.click(805,136)
pyautogui.typewrite('sissymahadev5@gmail.com')
pyautogui.press('tab')
pyautogui.typewrite('themorningstar')
pyautogui.press('enter')
sleep(2)
pyautogui.click(258,13)
pyautogui.typewrite('accounts.google.com')
pyautogui.press('enter')
sleep(7)
pyautogui.click(546,374)
pyautogui.typewrite('pratimarajput247')
pyautogui.press('enter')
sleep(3)
pyautogui.click(546,374)
pyautogui.typewrite('themorningstar')
pyautogui.press('enter')
sleep(10)
pyautogui.rightClick(581,298)
sleep(0.5)
pyautogui.click(586,305)
sleep(0.5)
pyautogui.click(813,285)
